#!/bin/sh
focused=$(xrdb ~/.Xresources -query all | grep color6 | cut -f2 | head -n 1)
normal=$(xrdb ~/.Xresources -query all | grep background | cut -f2 | head -n 1)

lc=$(xrandr | grep " connected" | wc -l)
echo $lc
if [ $lc = "1" ]
then
    xrandr --output eDP1 --mode 1920x1080 --output DP1 --off
    bspc monitor eDP1 -d I II III IV V
else
    xrandr --output DP1 --primary --mode 1920x1080 --rotate normal --output eDP1 --mode 1920x1080 --rotate normal --below DP1
    bspc monitor DP1 -d I II III IV V
    bspc monitor eDP1 -d VI VII VIII IX X
fi

bspc config border_radius           15  
bspc config focused_border_color	"$focused"
bspc config normal_border_color		"$normal"
bspc config border_width		    2
bspc config window_gap 			    4
bspc config focus_follows_pointer	true
bspc config top_padding             48
bspc config split_ratio			    0.52
bspc config borderless_monocle		true
bspc config gapless_monocle		    false 
bspc config single_monocle		    true
$HOME/.config/polybar/launch.sh &
bspwm
