#!/usr/bin/env bash
user="$USER@$(hostname)"
vol="$(amixer -D pulse get Master | grep '%' | head -n 1 | cut -d '[' -f 2 | cut -d '%' -f 1)"
bat="$(acpi | grep "Battery 0" | cut -d, -f2 | cut -d" " -f2)"
mem="$(free -m | tail -n 2 | head -n 1 | awk '{ print $3 }' | sed 's/$/M/')"
mem2="$(free -m | tail -n 2 | head -n 1 | awk '{ print $5 }' | sed 's/$/M/')"
date="$(date +"%a %F")"
time="$(date +"%H:%M %p")"
wifi="$(nmcli | grep ": connected" | awk '{print $4 }')"
bckl="$(xbacklight | awk '{print int($1+0.5)}')"
os="Endeavour"
kernel="$(uname -r | cut -f 1 -d '-')"
uptime="$(uptime | cut -f 1 -d ',' | sed -E 's/^[^,]*up *//; s/, *[[:digit:]]* users.*//; s/min/minutes/; s/([[:digit:]]+):0?([[:digit:]]+)/\1 hours, \2 minutes/')"
wm="bspwm"
pkg="$(pacman -Qq | wc -l)"
sh="$(echo $SHELL | cut -f 3 -d '/')"
dunstify --replace 301 -u critical " ${user}"$'\n'" ${date}"$'\n'" ${time}"$'\n'" ${uptime}"$'\n'" ${os}"$'\n'" ${kernel}"$'\n'" ${wm}"$'\n'" ${pkg}"$'\n'" ${sh}"$'\n'" Volume: ${vol}%"$'\n'" Battery: ${bat}"$'\n'" Used memory: ${mem}"$'\n'" Shared memory: ${mem2}"$'\n'"直 Wi-Fi: ${wifi}"$'\n'" Backlight: ${bckl}%"
